import {alpha} from "@mui/material/styles";

const getSectionHeaderAccent = (props) => props.theme.sectionHeader?.accent || props.theme.palette.primary.main;
const getSectionHeaderGradient = (props) => {
    if(props.theme.gradients?.sectionHeader){
        return props.theme.gradients.sectionHeader;
    }
    const headerTextColor = props.theme.color.header.text || props.theme.palette.text.primary;
    return `linear-gradient(90deg, ${alpha(props.theme.palette.primary.main, props.theme.palette.mode === "dark" ? 0.28 : 0.18)} 0%, ${alpha(props.theme.palette.primary.main, props.theme.palette.mode === "dark" ? 0.12 : 0.08)} 48%, ${alpha(headerTextColor, props.theme.palette.mode === "dark" ? 0.055 : 0.04)} 100%)`;
};
const getSubtleAccentGradient = (props) => props.theme.gradients?.subtleAccent ||
    `linear-gradient(135deg, ${alpha(props.theme.palette.primary.main, props.theme.palette.mode === "dark" ? 0.13 : 0.075)} 0%, ${alpha(props.theme.palette.background.paper, 0)} 62%)`;
const getSubtleAccentHorizontalGradient = (props) => props.theme.gradients?.subtleAccentHorizontal ||
    `linear-gradient(90deg, ${alpha(props.theme.palette.primary.main, props.theme.palette.mode === "dark" ? 0.12 : 0.07)} 0%, ${alpha(props.theme.palette.background.paper, 0)} 100%)`;

const modeAlpha = (color, mode, darkOpacity, lightOpacity) => alpha(color, mode === "dark" ? darkOpacity : lightOpacity);
const createToneVariables = (name, color, mode) => ({
    [`--mythic-effect-${name}-subtle`]: modeAlpha(color, mode, 0.1, 0.06),
    [`--mythic-effect-${name}-soft`]: modeAlpha(color, mode, 0.2, 0.12),
    [`--mythic-effect-${name}-medium`]: modeAlpha(color, mode, 0.36, 0.24),
    [`--mythic-effect-${name}-strong`]: modeAlpha(color, mode, 0.52, 0.36),
    [`--mythic-effect-${name}-emphasis`]: modeAlpha(color, mode, 0.72, 0.52),
});

// Values that cannot be expressed as direct appearance/foundation paths live
// under purpose-based effect names. This is a compile-time theme factory
// helper; it is not a compatibility or runtime style-injection layer.
export const createDerivedThemeVariables = (theme) => {
    const props = {theme};
    return {
        ...createToneVariables("accent", theme.palette.primary.main, theme.palette.mode),
        ...createToneVariables("danger", theme.palette.error.main, theme.palette.mode),
        ...createToneVariables("info", theme.palette.info.main, theme.palette.mode),
        ...createToneVariables("neutral", theme.palette.secondary.main, theme.palette.mode),
        ...createToneVariables("success", theme.palette.success.main, theme.palette.mode),
        ...createToneVariables("warning", theme.palette.warning.main, theme.palette.mode),
        "--mythic-color-table-border": theme.table?.border || theme.color.application.border,
        "--mythic-color-table-border-soft": theme.table?.borderSoft || theme.color.application.border,
        "--mythic-effect-backdrop": modeAlpha(theme.palette.background.default, theme.palette.mode, 0.7, 0.52),
        "--mythic-effect-highlight-border": modeAlpha(theme.palette.common.white, theme.palette.mode, 0.12, 0.18),
        "--mythic-effect-muted-text-medium": alpha(theme.palette.text.secondary, 0.35),
        "--mythic-effect-muted-text-strong": alpha(theme.palette.text.secondary, 0.55),
        "--mythic-effect-muted-text-subtle": modeAlpha(theme.palette.text.secondary, theme.palette.mode, 0.12, 0.08),
        "--mythic-effect-shadow-soft": modeAlpha(theme.palette.common.black, theme.palette.mode, 0.22, 0.08),
        "--mythic-effect-shadow-strong": modeAlpha(theme.palette.common.black, theme.palette.mode, 0.32, 0.12),
        "--mythic-effect-shadow-subtle": modeAlpha(theme.palette.common.black, theme.palette.mode, 0.18, 0.06),
        "--mythic-effect-surface-elevated": modeAlpha(theme.palette.background.paper, theme.palette.mode, 0.82, 0.88),
        "--mythic-effect-surface-opaque": modeAlpha(theme.palette.background.paper, theme.palette.mode, 0.96, 0.98),
        "--mythic-effect-surface-translucent": modeAlpha(theme.palette.background.paper, theme.palette.mode, 0.72, 0.82),
        "--mythic-effect-text-ghost": modeAlpha(theme.palette.text.primary, theme.palette.mode, 0.045, 0.035),
        "--mythic-effect-text-medium": modeAlpha(theme.palette.text.primary, theme.palette.mode, 0.5, 0.38),
        "--mythic-effect-text-soft": modeAlpha(theme.palette.text.primary, theme.palette.mode, 0.28, 0.2),
        "--mythic-effect-text-subtle-fill": modeAlpha(theme.palette.text.primary, theme.palette.mode, 0.08, 0.06),
        "--mythic-radius": `${theme.shape.borderRadius}px`,
        "--mythic-error-main": ((props) => props.theme.palette.error.main)(props),
        "--mythic-nav-background": ((props) => props.theme.navigation.background)(props),
        "--mythic-nav-background-color": ((props) => props.theme.navigation.backgroundColor)(props),
        "--mythic-nav-hover": ((props) => props.theme.navigation.hover)(props),
        "--mythic-nav-icon": ((props) => props.theme.navigation.icon)(props),
        "--mythic-nav-muted": ((props) => props.theme.navigation.muted)(props),
        "--mythic-nav-text": ((props) => props.theme.navigation.text)(props),
        "--mythic-effect-action-disabled-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.03)" : "rgba(0,0,0,0.02)")(props),
        "--mythic-effect-action-hover-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.1)" : "rgba(0,0,0,0.06)")(props),
        "--mythic-effect-adaptive-info-accent": ((props) => props.theme.palette.mode === "dark" ? props.theme.palette.info.light : props.theme.palette.info.dark || props.theme.palette.info.main)(props),
        "--mythic-effect-adaptive-info-accent-emphasis": ((props) => alpha(props.theme.palette.mode === "dark" ? props.theme.palette.info.light : props.theme.palette.info.dark || props.theme.palette.info.main, props.theme.palette.mode === "dark" ? 0.86 : 0.68))(props),
        "--mythic-effect-adaptive-info-accent-medium": ((props) => alpha(props.theme.palette.mode === "dark" ? props.theme.palette.info.light : props.theme.palette.info.dark || props.theme.palette.info.main, props.theme.palette.mode === "dark" ? 0.34 : 0.22))(props),
        "--mythic-effect-adaptive-info-accent-soft": ((props) => alpha(props.theme.palette.mode === "dark" ? props.theme.palette.info.light : props.theme.palette.info.dark || props.theme.palette.info.main, props.theme.palette.mode === "dark" ? 0.24 : 0.14))(props),
        "--mythic-effect-adaptive-info-accent-strong": ((props) => alpha(props.theme.palette.mode === "dark" ? props.theme.palette.info.light : props.theme.palette.info.dark || props.theme.palette.info.main, props.theme.palette.mode === "dark" ? 0.72 : 0.5))(props),
        "--mythic-effect-adaptive-primary-accent": ((props) => props.theme.palette.mode === "dark" ? props.theme.palette.primary.light : props.theme.palette.primary.dark || props.theme.palette.primary.main)(props),
        "--mythic-effect-adaptive-primary-accent-soft": ((props) => alpha(props.theme.palette.mode === "dark" ? props.theme.palette.primary.light : props.theme.palette.primary.dark || props.theme.palette.primary.main, props.theme.palette.mode === "dark" ? 0.24 : 0.14))(props),
        "--mythic-effect-adaptive-primary-accent-strong": ((props) => alpha(props.theme.palette.mode === "dark" ? props.theme.palette.primary.light : props.theme.palette.primary.dark || props.theme.palette.primary.main, props.theme.palette.mode === "dark" ? 0.72 : 0.5))(props),
        "--mythic-effect-api-token-resource-wildcard-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.045)" : "rgba(0,0,0,0.03)")(props),
        "--mythic-effect-api-token-value-input-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(0,0,0,0.26)" : "rgba(15,23,42,0.045)")(props),
        "--mythic-effect-browser-script-editor-bg": ((props) => props.theme.palette.mode === "dark" ? alpha(props.theme.palette.common.black, 0.18) : alpha(props.theme.palette.common.white, 0.62))(props),
        "--mythic-effect-browser-script-splitter-bg": ((props) => props.theme.palette.mode === "dark" ? alpha(props.theme.palette.common.white, 0.1) : alpha(props.theme.palette.common.black, 0.08))(props),
        "--mythic-effect-browser-script-target-panel-shadow": ((props) => props.theme.palette.mode === "dark" ? "none" : "0 8px 18px rgba(15, 23, 42, 0.04)")(props),
        "--mythic-effect-c2-action-subtitle-text": ((props) => alpha(props.theme.color.header.text || props.theme.palette.text.secondary, 0.76))(props),
        "--mythic-effect-c2-agent-focus-gradient": ((props) => `linear-gradient(180deg, ${alpha(props.theme.palette.primary.main, props.theme.palette.mode === "dark" ? 0.2 : 0.1)} 0%, ${alpha(props.theme.palette.background.paper, 0)} 100%)`)(props),
        "--mythic-effect-c2-edge-chip-shadow": ((props) => props.theme.palette.mode === "dark" ? "0 6px 18px rgba(0,0,0,0.34)" : "0 6px 14px rgba(15, 23, 42, 0.16)")(props),
        "--mythic-effect-c2-edge-empty-selection-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.04)" : "rgba(0,0,0,0.025)")(props),
        "--mythic-effect-c2-edge-label-focus-shadow": ((props) => props.theme.palette.mode === "dark" ? "drop-shadow(0 0 6px rgba(255,255,255,0.18))" : "drop-shadow(0 2px 6px rgba(15,23,42,0.18))")(props),
        "--mythic-effect-c2-edge-path-focus-shadow": ((props) => props.theme.palette.mode === "dark" ? "drop-shadow(0 0 4px rgba(255,255,255,0.14))" : "drop-shadow(0 1px 3px rgba(15,23,42,0.18))")(props),
        "--mythic-effect-c2-group-edge-summary-shadow": ((props) => props.theme.palette.mode === "dark" ? "0 8px 22px rgba(0,0,0,0.36)" : "0 8px 18px rgba(15, 23, 42, 0.18)")(props),
        "--mythic-effect-c2-group-header-gradient": ((props) => `linear-gradient(180deg, ${alpha(props.theme.sectionHeader?.background || props.theme.palette.background.paper, props.theme.palette.mode === "dark" ? 0.96 : 0.98)} 0%, ${alpha(props.theme.palette.background.paper, props.theme.palette.mode === "dark" ? 0.86 : 0.94)} 100%)`)(props),
        "--mythic-effect-c2-group-node-shadow": ((props) => props.theme.palette.mode === "dark" ? "0 10px 28px rgba(0,0,0,0.22)" : "0 10px 24px rgba(15, 23, 42, 0.08)")(props),
        "--mythic-effect-c2-route-error-gradient": ((props) => `linear-gradient(90deg, ${alpha(props.theme.palette.error.main, props.theme.palette.mode === "dark" ? 0.18 : 0.09)} 0%, ${alpha(props.theme.palette.background.paper, 0)} 70%)`)(props),
        "--mythic-effect-c2-route-success-gradient": ((props) => `linear-gradient(90deg, ${alpha(props.theme.palette.success.main, props.theme.palette.mode === "dark" ? 0.16 : 0.08)} 0%, ${alpha(props.theme.palette.background.paper, 0)} 70%)`)(props),
        "--mythic-effect-c2-route-warning-gradient": ((props) => `linear-gradient(90deg, ${alpha(props.theme.palette.warning.main, props.theme.palette.mode === "dark" ? 0.18 : 0.09)} 0%, ${alpha(props.theme.palette.background.paper, 0)} 70%)`)(props),
        "--mythic-effect-card-hover-shadow": ((props) => props.theme.palette.mode === "dark" ? `inset 0 1px 0 ${alpha(props.theme.palette.common.white, 0.055)}, 0 8px 18px ${alpha(props.theme.palette.common.black, 0.18)}` : `0 8px 18px ${alpha(props.theme.palette.common.black, 0.08)}`)(props),
        "--mythic-effect-chat-system-warning-gradient": ((props) => `linear-gradient(135deg, ${alpha(props.theme.palette.warning.main, props.theme.palette.mode === "dark" ? 0.34 : 0.24)} 0%, ${alpha(props.theme.palette.warning.main, props.theme.palette.mode === "dark" ? 0.18 : 0.12)} 58%, ${alpha(props.theme.palette.warning.main, props.theme.palette.mode === "dark" ? 0.08 : 0.06)} 100%)`)(props),
        "--mythic-effect-code-block-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(0,0,0,0.36)" : "rgba(15,23,42,0.06)")(props),
        "--mythic-effect-code-snippet-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.045)" : "rgba(0,0,0,0.035)")(props),
        "--mythic-effect-compact-chip-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.055)" : "rgba(0,0,0,0.035)")(props),
        "--mythic-effect-context-menu-shadow": ((props) => props.theme.palette.mode === 'dark' ? "0 18px 48px rgba(0, 0, 0, 40%)" : "0 18px 48px rgba(15, 23, 42, 12%)")(props),
        "--mythic-effect-control-soft-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.035)")(props),
        "--mythic-effect-control-subtle-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.045)" : "rgba(0,0,0,0.025)")(props),
        "--mythic-effect-dashboard-card-shadow": ((props) => props.theme.palette.mode === "dark" ? "inset 0 1px 0 rgba(255,255,255,0.04)" : "0 1px 2px rgba(15,23,42,0.06)")(props),
        "--mythic-effect-dashboard-edit-toolbar-bg": ((props) => props.theme.color.header.surface || props.theme.surfaces?.muted || props.theme.palette.background.paper)(props),
        "--mythic-effect-dashboard-loading-card-shadow": ((props) => props.theme.palette.mode === "dark" ? "0 12px 28px rgba(0,0,0,0.35)" : "0 12px 28px rgba(15,23,42,0.14)")(props),
        "--mythic-effect-dashboard-loading-overlay-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(0,0,0,0.45)" : "rgba(255,255,255,0.55)")(props),
        "--mythic-effect-dashboard-table-subtle-bg": ((props) => props.theme.palette.mode === "dark" ? alpha(props.theme.palette.common.white, 0.018) : alpha(props.theme.palette.common.black, 0.01))(props),
        "--mythic-effect-dashboard-widget-option-shadow": ((props) => props.theme.palette.mode === "dark" ? "inset 0 1px 0 rgba(255,255,255,0.04)" : "0 1px 2px rgba(15,23,42,0.05)")(props),
        "--mythic-effect-empty-panel-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.035)" : "rgba(0,0,0,0.02)")(props),
        "--mythic-effect-eventing-code-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(0,0,0,0.24)" : "rgba(255,255,255,0.72)")(props),
        "--mythic-effect-eventing-code-gutter-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.04)" : "rgba(0,0,0,0.035)")(props),
        "--mythic-effect-eventing-detail-chip-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.08)" : "rgba(255,255,255,0.72)")(props),
        "--mythic-effect-eventing-empty-section-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.018)" : "rgba(0,0,0,0.01)")(props),
        "--mythic-effect-eventing-metadata-panel-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.02)" : "rgba(0,0,0,0.012)")(props),
        "--mythic-effect-eventing-required-field-border": ((props) => props.theme.palette.warning.main + "45")(props),
        "--mythic-effect-eventing-runas-chip-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.04)")(props),
        "--mythic-effect-eventing-sidebar-count-bg": ((props) => props.theme.palette.primary.main + "38")(props),
        "--mythic-effect-eventing-step-list-item-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.026)" : "rgba(0,0,0,0.018)")(props),
        "--mythic-effect-eventing-workflow-shadow": ((props) => props.theme.palette.mode === "dark" ? "inset 0 1px 0 rgba(255,255,255,0.055)" : "inset 0 1px 0 rgba(255,255,255,0.78)")(props),
        "--mythic-effect-gradient-subtle-accent": ((props) => getSubtleAccentGradient(props))(props),
        "--mythic-effect-gradient-subtle-accent-horizontal": ((props) => getSubtleAccentHorizontalGradient(props))(props),
        "--mythic-effect-grid-filter-title-bg": ((props) => props.theme.color.header.surface || props.theme.surfaces?.muted || props.theme.palette.background.default)(props),
        "--mythic-effect-grid-header-indicator-shadow": ((props) => props.theme.palette.mode === "dark" ? "0 0 0 1px rgba(255,255,255,0.04)" : "0 1px 2px rgba(15, 23, 42, 0.08)")(props),
        "--mythic-effect-grid-root-shadow": ((props) => props.theme.palette.mode === "dark" ? "none" : "0 8px 18px rgba(15, 23, 42, 0.035)")(props),
        "--mythic-effect-inline-parameter-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.035)" : "rgba(0,0,0,0.018)")(props),
        "--mythic-effect-installed-service-header-bg": ((props) => props.theme.color.header.surface || props.theme.palette.background.contrast)(props),
        "--mythic-effect-item-muted-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.035)" : "rgba(0,0,0,0.025)")(props),
        "--mythic-effect-json-key-cell-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.018)" : "rgba(0,0,0,0.012)")(props),
        "--mythic-effect-neutral-subtle-bg": ((props) => props.theme.palette.mode === "dark" ? alpha(props.theme.palette.common.white, 0.045) : alpha(props.theme.palette.common.black, 0.028))(props),
        "--mythic-effect-output-control-bg": ((props) => alpha(props.theme.color.tasking.outputText || props.theme.palette.text.primary, props.theme.palette.mode === "dark" ? 0.1 : 0.07))(props),
        "--mythic-effect-output-control-border": ((props) => alpha(props.theme.color.tasking.outputText || props.theme.palette.text.primary, props.theme.palette.mode === "dark" ? 0.2 : 0.16))(props),
        "--mythic-effect-output-control-text": ((props) => props.theme.color.tasking.outputText || props.theme.palette.text.primary)(props),
        "--mythic-effect-output-editor-bg": ((props) => props.theme.color.tasking.outputBackground + "20")(props),
        "--mythic-effect-output-empty-hint-text": ((props) => alpha(props.theme.color.tasking.outputText || props.theme.palette.text.primary, 0.58))(props),
        "--mythic-effect-output-frame-border": ((props) => alpha(props.theme.color.tasking.outputText || props.theme.palette.text.primary, props.theme.palette.mode === "dark" ? 0.24 : 0.2))(props),
        "--mythic-effect-output-muted-text": ((props) => alpha(props.theme.color.tasking.outputText || props.theme.palette.text.primary, 0.72))(props),
        "--mythic-effect-output-toolbar-bg": ((props) => alpha(props.theme.color.tasking.outputBackground || props.theme.palette.background.paper, props.theme.palette.mode === "dark" ? 0.86 : 0.72))(props),
        "--mythic-effect-output-warning-text": ((props) => alpha(props.theme.color.tasking.outputText || props.theme.palette.text.primary, 0.82))(props),
        "--mythic-effect-primary-action-hover": ((props) => props.theme.palette.primary.dark || props.theme.palette.primary.main)(props),
        "--mythic-effect-process-inspector-shadow": ((props) => props.theme.palette.mode === "dark" ? "0 -10px 24px rgba(0,0,0,0.22)" : "0 -10px 24px rgba(15,23,42,0.06)")(props),
        "--mythic-effect-raw-select-row-bg": ((props) => props.theme.surfaces?.muted || alpha(props.theme.palette.text.primary, props.theme.palette.mode === "dark" ? 0.045 : 0.035))(props),
        "--mythic-effect-reorder-drag-handle-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.03)")(props),
        "--mythic-effect-reorder-row-dragging-shadow": ((props) => props.theme.palette.mode === "dark" ? "0 12px 28px rgba(0,0,0,0.32)" : "0 12px 28px rgba(15,23,42,0.14)")(props),
        "--mythic-effect-response-action-hover-bg": ((props) => props.theme.palette.mode === "dark" ? alpha(props.theme.palette.common.white, 0.085) : alpha(props.theme.palette.common.black, 0.052))(props),
        "--mythic-effect-row-disabled-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.025)" : "rgba(0,0,0,0.018)")(props),
        "--mythic-effect-search-result-metric-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.045)" : "rgba(0,0,0,0.028)")(props),
        "--mythic-effect-section-header-accent": (getSectionHeaderAccent)(props),
        "--mythic-effect-section-header-accent-soft": ((props) => alpha(getSectionHeaderAccent(props), props.theme.palette.mode === "dark" ? 0.34 : 0.2))(props),
        "--mythic-effect-section-header-accent-strong": ((props) => alpha(getSectionHeaderAccent(props), props.theme.palette.mode === "dark" ? 0.55 : 0.38))(props),
        "--mythic-effect-section-header-gradient": (getSectionHeaderGradient)(props),
        "--mythic-effect-section-toolbar-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.025)" : "rgba(0,0,0,0.012)")(props),
        "--mythic-effect-selected-task-bg": ((props) => props.theme.color.table.selectedCallback + "DD")(props),
        "--mythic-effect-shadows-1": ((props) => props.theme.shadows[1])(props),
        "--mythic-effect-single-task-remove-bg": ((props) => props.theme.palette.mode === "dark" ? alpha(props.theme.palette.error.main, 0.14) : alpha(props.theme.palette.error.main, 0.08))(props),
        "--mythic-effect-success-stripe-gradient": ((props) => `repeating-linear-gradient(90deg, ${props.theme.palette.success.main} 0, ${props.theme.palette.success.main} 5px, transparent 5px, transparent 9px)`)(props),
        "--mythic-effect-summary-panel-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.025)" : "rgba(0,0,0,0.014)")(props),
        "--mythic-effect-table-empty-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.03)" : "rgba(0,0,0,0.018)")(props),
        "--mythic-effect-table-toolbar-search-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.028)" : "rgba(0,0,0,0.012)")(props),
        "--mythic-effect-task-parameter-chip-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.055)" : "rgba(0,0,0,0.032)")(props),
        "--mythic-effect-tasking-composer-shadow": ((props) => props.theme.palette.mode === "dark" ? "0 -10px 28px rgba(0, 0, 0, 0.24)" : "0 -10px 28px rgba(15, 23, 42, 0.06)")(props),
        "--mythic-effect-tasking-filter-clear-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.025)")(props),
        "--mythic-effect-tasking-filter-selected-chip-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.07)" : "rgba(0,0,0,0.045)")(props),
        "--mythic-effect-tasking-visibility-panel-bg": ((props) => props.theme.palette.mode === "dark" ? "rgba(255,255,255,0.035)" : "rgba(15,23,42,0.025)")(props),
        "--mythic-effect-toolbar-toggle-selected-bg": ((props) => props.theme.palette.primary.main + "55")(props),
        "--mythic-effect-typography-font-family": ((props) => props.theme.typography.fontFamily)(props),
        "--mythic-warning-main": ((props) => props.theme.palette.warning.main)(props),
    };
};
